apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubys-core-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubys-core-web-app
  template:
    metadata:
      labels:
        app: ubys-core-web-app
    spec:
      containers:
        - name: webapp
          image: harbor.ikc.edu.tr/ubys-core-web-app/ubys-core-web-app:1.0.0
          ports:
            - containerPort: 80