apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubys-core-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubys-core-web-app
  template:
    metadata:
      labels:
        app: ubys-core-web-app
    spec:
      containers:
        - name: webapp
          image: 192.168.95.211/ubys-core-web-app/ubys-core-web-app:1.0.0
          ports:
            - containerPort: 80